### ISSUE TITLE
Questions about input templates in inference

### ISSUE THREAD

**Issue by skleee** [WangXFng/ELMRec#2]
Thanks for your great work!

I have found that you are using classes SeqBatchify, ExpBatchify, and TopNBatchify to infer the model, which defines a user template as `self.user_template = 'user_{} item_{}'`. 

I wonder if the input sentence template for the model at inference is fixed to `user_{} item_{}`.  Are the other remaining sentences in [model/templates.py](https://github.com/WangXFng/ELMRec/blob/main/model/templates.py) only used for training?

**Comment by WangXFng** [comment]
Thank you for your question!
You are right that the input template at inference stage is fixed to `user_{} item_{}`. Because the ELMRec model takes POD (https://github.com/lileipisces/POD) as its backbone. The POD distills the textual prompts into continuous prompt vector (prefix vector), reducing inference time without compromising performance. Thus, the distilled template is very short (prompt vector + `user_{} item_{}`), while the other remaining templates are only used for training.

**Comment by skleee** [comment]
Thank you for your quick answer. It helps a lot. Thank you so much!
